### ISSUE TITLE
Improve Onboarding Screen 

### ISSUE THREAD

**Issue by Aditya-gupta99** [hieuwu/android-groceries-store#111]
**Is your feature request related to a problem? Please describe.**
When I opened the app, I didn't find any detailed information about how the app works.

**Describe the solution you'd like**
To demonstrate how the app works, I would like to use viewpager2 in order to display all the features of the app.

**Describe alternatives you've considered**
I can also implement a bubble showcase to show all the hidden features of the app.

**Comment by Aditya-gupta99** [comment]
Please assign me this issue

**Comment by hieuwu** [comment]
> Please assign me this issue

Also confirm my understanding about your idea man

**Comment by Aditya-gupta99** [comment]
Yes i understood .
