### ISSUE TITLE
Migrate LiveData to StateFlow in ViewModels and observe in Fragments

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#112]
**Is your feature request related to a problem? Please describe.**
To adapt Android modern development, we need to migrate from LiveData to StateFlow

**Describe the solution you'd like**
It would be great if we can just make 1 or some screens to be fully using Flow so that other developer can join and do it folowing the convention

**Describe alternatives you've considered**
None

**Comment by DeKaN** [comment]
Hi, can I take this issue?

**Comment by hieuwu** [comment]
> Hi, can I take this issue?

Great!!! This is yours. Please pull the latest code frequently because many developers are working on this. It's ok to migrate first 1 or 2 screens then the rest.
