### ISSUE TITLE
Improve Shop page

### ISSUE THREAD

**Issue by Aditya-gupta99** [hieuwu/android-groceries-store#114]
**Is your feature request related to a problem? Please describe.**
On the shop home page when you are entering the app, you will notice that the view pager photo does not have any motion at all. In order to change it, the user had to scroll from left to right in order to do so.

**Describe the solution you'd like**
I will use view pager 2 . This will allow me to add logic to make it move. and I will also make the shop page more user-friendly.

**Comment by hieuwu** [comment]
@Aditya-gupta99  Cool Please also find others images to replace the current one. We need to put some attractive banner this. Hopefully you can do this as well. Maybe some promotion with color and some kinds of it

**Comment by Aditya-gupta99** [comment]
ya sure.

**Comment by hieuwu** [comment]
Closed. Fixed in #125
