### ISSUE TITLE
Improve laggy effect of the cart list when edit item

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#115]
**Is your feature request related to a problem? Please describe.**
Currently, int the cart list screen, when edit item like increase or decrease quantity of each item, it has a fade effect

**Describe the solution you'd like**
It would be nice if we can make this more smooth

**Issue**

https://user-images.githubusercontent.com/43868345/193828656-f13eced8-e56d-4d49-a72f-de044ab4ee61.mp4

**Comment by AmartyaSingh97** [comment]
Can you please explain specifically what type of animation you want for it or should I try some ideas and propose them before you?

**Comment by hieuwu** [comment]
> Can you please explain specifically what type of animation you want for it or should I try some ideas and propose them before you?

I just updated video of the item in list. The item have flicker affect whenever I edit the quantity
