### ISSUE TITLE
Provide dependencies at right scope

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#116]
**Is your feature request related to a problem? Please describe.**
Currently every dependencies is provided at @Singleton scope. This is not a good approach. Some components like UseCase can be provided only when we need to use it in ViewModel

**Describe the solution you'd like**
Provide UseCases at ViewModelScope instead of Singleton

**Describe alternatives you've considered**
None

**Comment by Devendra34** [comment]
Hi @hieuwu, 
Can I try for this issue?
