### ISSUE TITLE
Improve explore page

### ISSUE THREAD

**Issue by Aditya-gupta99** [hieuwu/android-groceries-store#117]
**Is your feature request related to a problem? Please describe.**
When you search for something in the explore navigation, then switch to the main navigation and return to explore again after searching for something in the explore navigation. It is likely that you will face a recycle view that will have some bugs in it.

**Describe the solution you'd like**
I will make it work perfectly will make sure that everything works perfectly. I'll go through the code, I'm confident that I'll fix this. I'll also make the search bar more user-friendly.

**Comment by Aditya-gupta99** [comment]
![issue](https://user-images.githubusercontent.com/94394661/193416011-06ce3ff1-2d90-4811-a180-25fa0e903820.jpeg)

**Comment by hieuwu** [comment]
@Aditya-gupta99 Thank you for pointing this out. Please attach screenshots for comparision after you complete

**Comment by hieuwu** [comment]
Closed. Added in #123
