### ISSUE TITLE
Delete option in the cart not working.

### ISSUE THREAD

**Issue by AmartyaSingh97** [hieuwu/android-groceries-store#119]
**Describe the bug**
The delete option in the cart to remove items from the cart is not working. Also, the " - " button to decrease the number of items in the cart is not working when the number of items in the cart is 1. 

**To Reproduce**
1. Go to 'cart'
2. Click on 'delete option beside products'

**Expected behavior**
When the delete button beside the product is clicked, all the items must be removed from the cart. If the " - " button is pressed and the number of items is 1, the item should be deleted from the cart.

**Screenshots**
![Screenshot_20221001-222410_Groceries Store](https://user-images.githubusercontent.com/85061899/193420159-04cef1d1-dfbf-465c-bee9-a49d419719d8.jpg)
![Screenshot_20221001-221349_Groceries Store](https://user-images.githubusercontent.com/85061899/193420171-c1ae1d08-7e21-4ace-867b-cf68d97c03ac.jpg)

**Desktop (please complete the following information):**
-NA

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 11
 

**Additional context**
NA

**Comment by AmartyaSingh97** [comment]
I'll try to remove these bugs, please assign it to me.

**Comment by hieuwu** [comment]
> I'll try to remove these bugs, please assign it to me.

Sure. Thank you for discovering all the bugs. If you have any new feature that feasible for you, feel free to propose it. 🥳

**Comment by SanjaySargam** [comment]
Can I contribute?

**Comment by hieuwu** [comment]
> Can I contribute?

This issue has been assigned to @AmartyaSingh97 . You can pick one that no one is assigned

**Comment by hieuwu** [comment]
Closed. Fixed in #126
