### ISSUE TITLE
Use HiltViewModel to provide ViewModels

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#124]
**Is your feature request related to a problem? Please describe.**
Use HiltViewModel to provide ViewModels to avoid boilerplate code

**Describe the solution you'd like**
Use HiltViewModel

**Describe alternatives you've considered**
None

**Comment by Devendra34** [comment]
Hi @hieuwu,
I'm interested, does this issue targets to refactor the entire project for such migration or you have some better plan to go with bits and pieces

**Comment by hieuwu** [comment]
Hi @Devendra34 , actually this issuse target to be a starting point to refactor the entire project.  It's okay to complete 1 or 2 screens first, it would save your time.

**Comment by hieuwu** [comment]
@Devendra34 Do you want to work on this?

**Comment by Devendra34** [comment]
Hi @hieuwu, 
Yes I wanted to try for it

**Comment by hieuwu** [comment]
> Hi @hieuwu,
> Yes I wanted to try for it

Nice. You can work on it now
