### ISSUE TITLE
Improve Favourite page

### ISSUE THREAD

**Issue by Aditya-gupta99** [hieuwu/android-groceries-store#127]
**Is your feature request related to a problem? Please describe
The favorite fragment does not seem to be as user-friendly as it should be.

**Describe the solution you'd like**
As I work on it, I will strive to make it as user-friendly as possible.

**Comment by hieuwu** [comment]
> **Is your feature request related to a problem? Please describe The favorite fragment does not seem to be as user-friendly as it should be.
> 
> **Describe the solution you'd like** As I work on it, I will strive to make it as user-friendly as possible.

Could you please give me some hints about what you will do?

**Comment by Aditya-gupta99** [comment]
I will change the Cardview to make the favorite list look better. I would like to change the orientation of the action bar to match the overall theme.

**Comment by hieuwu** [comment]
Okay let's do it.

> Similar to the shop home page

**Comment by hieuwu** [comment]
Closed. Fixed in #129

**Comment by hieuwu** [comment]
@all-contributors please add @Aditya-gupta99 for his creativity in improving the favourite screen

**Comment by hieuwu** [comment]
@all-contributors please add @Aditya-gupta99 for design
