### ISSUE TITLE
Move dependencies to a Gradle version catalog

### ISSUE THREAD

**Issue by fejd** [hieuwu/android-groceries-store#141]
**Is your feature request related to a problem? Please describe.**
I'd like to convert the dependencies to use the Gradle version catalog feature.

**Describe the solution you'd like**
Move dependencies and plugins from the build.gradle files to a TOML file.

**Describe alternatives you've considered**
Dependencies could also be located in buildSrc, however version catalog is a "native" Gradle feature.

**Additional context**

**Comment by hieuwu** [comment]
@fejd  good idea! I will assign this to you. Please also explain the reason you apply this in the PR. Happy coding!
