### ISSUE TITLE
Migrate Account feature from XML to Jetpack Compose

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#173]
Currently feature Account in `presentation/account` package is implemented with XML view system. Let's convert it to Jetpack Compose. See `shop` feature for reference

**Comment by Devendra34** [comment]
Hi @hieuwu,
Can I pick this up as well?

**Comment by hieuwu** [comment]
> Hi @hieuwu, Can I pick this up as well?

Yeah sure. And also feel free to raise any idea to improve the projec!

**Comment by Devendra34** [comment]
Hi @hieuwu,
Looks like the APIs are not working, 
Can you please help to make the server running or Am I missing something for setting them up?
