### ISSUE TITLE
Migrate Checkout feature to Jetpack Compose

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#174]
Currently feature Account in `presentation/checkout` package is implemented with XML view system. Let's convert it to Jetpack Compose. See `shop` feature for reference

**Comment by patthhar** [comment]
Hi, I would love to work on this issue! Can you assign it to me?

**Comment by hieuwu** [comment]
> Hi, I would love to work on this issue! Can you assign it to me?

Sure. Let me know if uou need any support
