### ISSUE TITLE
Migrate Notification Settings feature to Jetpack Compose

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#175]
Currently feature Account in `presentation/notificationsettings` package is implemented with XML view system. Let's convert it to Jetpack Compose. See `shop` feature for reference

**Comment by Yashraj254** [comment]
can i work on this issue?

**Comment by hieuwu** [comment]
> can i work on this issue?

Sure! Go with it Yash. Let me know if you need any support
