### ISSUE TITLE
Migrate onboarding to Jetpack Compose

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#176]
Currently feature Account in `presentation/onboarding` package is implemented with XML view system. Let's convert it to Jetpack Compose. See `shop` feature for reference

**Comment by Devendra34** [comment]
Hi @hieuwu,
Can I work on this Issue?

**Comment by hieuwu** [comment]
> Hi @hieuwu,
> Can I work on this Issue?

Sure. I assigned it to you. Let me know if you need any help

**Comment by Devendra34** [comment]
Hi @hieuwu,
What is the expect primary button disabled color? Is it `light_gray` or `transparent`?
From the `primary_button.xml` code it seems like `light_gray`, but when we run the app or even in andriod studio xml previews, it looks like transparent.

Observe the preview in this screenshot
<img width="496" alt="Screenshot 2023-10-01 at 12 49 53 PM" src="https://github.com/hieuwu/android-groceries-store/assets/51832211/3fd0321e-dd26-48d1-9559-309d6523a5cf">

`primary_button.xml` snippet for disabled color
<img width="496" alt="Screenshot 2023-10-01 at 12 51 26 PM" src="https://github.com/hieuwu/android-groceries-store/assets/51832211/685cd04e-25ce-4e1f-a702-ee4d7168dbae">

**Comment by Devendra34** [comment]
> Hi @hieuwu, What is the expected primary button disabled color? Is it `light_gray` or `transparent`? From the `primary_button.xml` code it seems like `light_gray`, but when we run the app or even in andriod studio xml previews, it looks like transparent.
> 
> Observe the preview in this screenshot <img alt="Screenshot 2023-10-01 at 12 49 53 PM" width="496" src="https://user-images.githubusercontent.com/51832211/271814148-3fd0321e-dd26-48d1-9559-309d6523a5cf.png">
> 
> `primary_button.xml` snippet for disabled color <img alt="Screenshot 2023-10-01 at 12 51 26 PM" width="496" src="https://user-images.githubusercontent.com/51832211/271814188-685cd04e-25ce-4e1f-a702-ee4d7168dbae.png">

Compared with `fragment_account.xml`, the property `app:backgroundTint="@null"` was missing in activity_onboarding.xml'. Because of this the disabled color was not updated.

Going forward with `light_gray` color in compose. The xml file will be anyhow deleted.

**Comment by hieuwu** [comment]
> Hi @hieuwu, What is the expected primary button disabled color? Is it `light_gray` or `transparent`? From the `primary_button.xml` code it seems like `light_gray`, but when we run the app or even in andriod studio xml previews, it looks like transparent.
> 
> Observe the preview in this screenshot <img alt="Screenshot 2023-10-01 at 12 49 53 PM" width="496" src="https://user-images.githubusercontent.com/51832211/271814148-3fd0321e-dd26-48d1-9559-309d6523a5cf.png">
> 
> `primary_button.xml` snippet for disabled color <img alt="Screenshot 2023-10-01 at 12 51 26 PM" width="496" src="https://user-images.githubusercontent.com/51832211/271814188-685cd04e-25ce-4e1f-a702-ee4d7168dbae.png">

Yeah good catch @Devendra34 . Let's go with your solution because that makes sense

**Comment by Devendra34** [comment]
Thanks for the confirmation @hieuwu.
I have raise #179 based on our discussion
