### ISSUE TITLE
Migrate product list to Jetpack Compose

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#177]
Currently feature Account in `presentation/productlist` package is implemented with XML view system. Let's convert it to Jetpack Compose. See `shop` feature for reference

**Comment by DeKaN** [comment]
Hi, can I take the issue?

**Comment by hieuwu** [comment]
> Hi, can I take the issue?

Sure. I assigned it to you. Let me know if you need any help

**Comment by DeKaN** [comment]
@hieuwu What library do you prefer for loading images in Compose `io.coil-kt:coil-compose:2.4.0` or  `com.github.bumptech.glide:compose:1.0.0-beta01`?
I see Glide in the project, but only the first beta for Compose has been released.

**Comment by hieuwu** [comment]
> @hieuwu What library do you prefer for loading images in Compose `io.coil-kt:coil-compose:2.4.0` or `com.github.bumptech.glide:compose:1.0.0-beta01`? I see Glide in the project, but only the first beta for Compose has been released.

I would prefer current one from Glide as it is used. But if you see Coil is better then please go with Coil. Just make sure we can remove the depencency on Glide after using Coil

**Comment by DeKaN** [comment]
OK, I'll try with Glide
