### ISSUE TITLE
Introduce Kotlin lint (detekt)

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#181]
**Is your feature request related to a problem? Please describe.**
To make the code base to be consistent

**Comment by Kardelio** [comment]
Ooooo can i grab this issue?

**Comment by hieuwu** [comment]
> Ooooo can i grab this issue?

Sure Kar. Let’s do it

**Comment by Kardelio** [comment]
Awesome! thank you!
So just to be clear its about bring `detekt` in as a linter.
Is there anything more? Like implement into CI/CD or something more?

**Comment by hieuwu** [comment]
> Awesome! thank you! So just to be clear its about bring `detekt` in as a linter. Is there anything more? Like implement into CI/CD or something more?

Yeah adding it and being able to execute the command to see analyze is good eough. It would be nice if you can implement it into the GitHub action before build step. Many thanks Kar

**Comment by hieuwu** [comment]
Close as completed in #191
