### ISSUE TITLE
Cover unit test for use case GetCategoriesListUseCase.kt

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#194]
Currently there is no testing for use case. It would be nice if we can set up one and cover them

**Comment by hieuwu** [comment]
I did some in app/src/test/java/com/hieuwu/groceriesstore/domain/usecases/impl/GetProfileUseCaseImplTest.kt, you can start writing test following the convention.

**Comment by patthhar** [comment]
Hey, I have checked out the test case you wrote, can I begin with this useCase following the convention?

**Comment by hieuwu** [comment]
> Hey, I have checked out the test case you wrote, can I begin with this useCase following the convention?

Sure then.
