### ISSUE TITLE
Cover unit test for use case GetCurrentCartUseCase.kt

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#195]
Currently there is no testing for use case. It would be nice if we can set up one and cover them

**Comment by hieuwu** [comment]
I did some in app/src/test/java/com/hieuwu/groceriesstore/domain/usecases/impl/GetProfileUseCaseImplTest.kt, you can start writing test following the convention.

**Comment by patthhar** [comment]
Can I take this up as well?

**Comment by patthhar** [comment]
Done
