### ISSUE TITLE
Cover unit test for use case GetProductsListUseCase.kt

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#199]
Currently there is no testing for use case. It would be nice if we can set up one and cover them

**Comment by hieuwu** [comment]
I did some in app/src/test/java/com/hieuwu/groceriesstore/domain/usecases/impl/GetProfileUseCaseImplTest.kt, you can start writing test following the convention.

**Comment by krishnachaitanya0107** [comment]
Hi @hieuwu  ,

I would like to work on this issue , could you please assign it to me .

Thanks

**Comment by hieuwu** [comment]
> Hi @hieuwu ,
> 
> I would like to work on this issue , could you please assign it to me .
> 
> Thanks

Sure

**Comment by krishnachaitanya0107** [comment]
Hi , 

I can see some test cases already in the [GetProductsListUseCaseImplTest](https://github.com/hieuwu/android-groceries-store/blob/main/app/src/test/java/com/hieuwu/groceriesstore/domain/usecases/impl/GetProductsListUseCaseImplTest.kt) , so just wanted to check with you on whether we need to add any more test cases to test some particular functionality .

Thanks

**Comment by krishnachaitanya0107** [comment]
Hi @hieuwu  , 


Just wanted to follow up with you on this , could you please confirm on whether we need to add new test cases to (or) is the existing one sufficient ? 

Thanks

**Comment by hieuwu** [comment]
Hey it’s completed man. Great work
