### ISSUE TITLE
Cover unit test for use case GetProfileUseCase.kt

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#200]
Currently there is no testing for use case. It would be nice if we can set up one and cover them

**Comment by patthhar** [comment]
Hi, I would like to start with setting up testing for useCases in the app. Can you assign me this issue?

**Comment by hieuwu** [comment]
Hey I did some in app/src/test/java/com/hieuwu/groceriesstore/domain/usecases/impl/GetProfileUseCaseImplTest.kt, you can start writing test following the convention.

**Comment by patthhar** [comment]
Sure, which one should I start with?

**Comment by hieuwu** [comment]
> Sure, which one should I start with?

Whatever you want man ! 😂 For now you can pick simplest one first to save your time
