### ISSUE TITLE
SignUp Issue

### ISSUE THREAD

**Issue by lokified** [hieuwu/android-groceries-store#217]
Getting `sign in failed. Please try again` when i signup a new account. I have tried with two different emails.

**Comment by hieuwu** [comment]
> Getting `sign in failed. Please try again` when i signup a new account. I have tried with two different emails.

Could you please share how you set up your Supabase project?

**Comment by lokified** [comment]
i have setup supabase project but. on success an error message still shows. and for sign in snackbar is shown but the user is not logged in.

> I have not setup supabase project. I thought it is using your credentials.

**Comment by WizCoderr** [comment]
have you tried firebase?
