### ISSUE TITLE
Write unit tests for use cases

### ISSUE THREAD

**Issue by ishanvaghani** [hieuwu/android-groceries-store#233]
I just started an open source contribution, so please let me know if there is any bug or improvement that I can make.

**Comment by hieuwu** [comment]
Hi thank you for reaching out Ishan. There are some issues to cover unit test, if you want to. If not, you can start setting up the project and play around to discover things. If you see anything can be improved, feel free to raise an issue & propose solution for it. I'm open to any discussion.

**Comment by ishanvaghani** [comment]
Hey @hieuwu , I can start with setting up a project and exploring the app. I will go through the current unit test cases, then jump to writing unit test cases. Also, let me know which feature or code unit tests are pending.

**Comment by ishanvaghani** [comment]
I started writing unit tests for use cases, and I'll cover all the remaining use cases.

**Comment by ishanvaghani** [comment]
Closing this issue, Thanks @hieuwu for providing opportunity for contribution. I'm ready to contribute more on this project please assign me tasks if there is any.
