### ISSUE TITLE
Bug Report: Accepting Invalid Email Format in Text Field

### ISSUE THREAD

**Issue by HoangMinhKhoiPham** [hieuwu/android-groceries-store#245]
Describe the bug

The system allows the input of an invalid email format in the email text field, even when using fuzzing like '!7#%"#0=)$;%6;>638:>80"=</>(/:-(2<4 !:56856&?""11<7+%<%7,4.8,+&,,$,."5%<%76< -5'.

To Reproduce

Navigate to the email text field.
Enter the invalid email format '!7#%"#0=)$;%6;>638:>80"=</>(/:-(2<4 !:56856&?""11<7+%<%7,4.8,+&,,$,."5%<%76< -5'.
Proceed with any further steps as required by the system.
Observe that the system accepts the invalid email format without displaying an error message.
Expected behavior

The system should reject the input of an invalid email format and display an error message prompting the user to enter a valid email address.

Screenshots

N/A

Desktop (please complete the following information):

N/A

Smartphone (please complete the following information):

N/A

Additional context

Accepting invalid email formats poses a security risk and can lead to confusion for users. The system should enforce proper email format validation to ensure data integrity and security.

**Comment by hieuwu** [comment]
Initially it was inteded not to add data validation for simplicity. Thank you for your suggestion. This will be added shortly.

**Comment by DevJethava** [comment]
Hello, I can work on this

**Comment by hieuwu** [comment]
> Hello, I can work on this

Hey thanks for noticing. Please go for it!

**Comment by DevJethava** [comment]
Please assign me the issue @hieuwu. I'll start working on it.
