### ISSUE TITLE
Use ConstraintLayout for the whole layout files

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#35]
Currently, most of the UIs of the app is implemented with LinearLayout, RelativeLayout. This is not good for render performance because of nested level of XML tags
Need to use ConstraintLayout to improve this

**Comment by piyushkumar12111111** [comment]
assign this to me

**Comment by hieuwu** [comment]
@piyushkumar12111111  Sure. About this one, please provide all the screenshot that you touched to make sure things work properly

**Comment by SanjaySargam** [comment]
Can U plz assign me?

**Comment by hieuwu** [comment]
> Can U plz assign me?

@piyushkumar12111111  is working on this. If I don't see any progress in the next few days, I will asign it to you @SanjaySargam . In the meanwhile, you can consider other issues. Or may be clone the project, discover things, point out some points that could be improved and open an issue then tag me there

**Comment by SanjaySargam** [comment]
> > Can U plz assign me?
> 
> @piyushkumar12111111 is working on this. If I don't see any progress in the next few days, I will asign it to you @SanjaySargam . In the meanwhile, you can consider other issues. Or may be clone the project, discover things, point out some points that could be improved and open an issue then tag me there

Okkk Thank You
