### ISSUE TITLE
Avoid duplicate code of adding item to cart logic

### ISSUE THREAD

**Issue by hieuwu** [hieuwu/android-groceries-store#7]
Should avoid duplicate code for actions like adding item to cart. Especially in Explore and Shop screen

**Comment by NiranjanNlc** [comment]
I could not find HOME Fragment on your project . Could you please elaborate?

**Comment by hieuwu** [comment]
@NiranjanNlc Hi. I updated the description. It is the shop fragment

**Comment by NiranjanNlc** [comment]
Please asighn it to me

**Comment by hieuwu** [comment]
There you go @NiranjanNlc . Happy coding!

**Comment by NiranjanNlc** [comment]
Hey , i found the duplication while assighning adpater in SHopFragment. 
I have made a pull request .
Please have a look
